### PR TITLE
varonissaas: update logo files - update logo images for application

### PR DESCRIPTION
**Pull request by vkorenkov-varonis**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [n/a] Testing of all the changes has been performed (for bug fixes / features)
- [n/a] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [x] Other (please describe): logos

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- update logo images for application

### CODE REVIEW

**Comment by vkorenkov-varonis** [comment]
Please, can you tell how to change a logo image in the marketplace. The logo in marketplace should be squared and doesn't contain the name of the company. I have this logo, but I did not find the way how to configure settings to use it in the marketplace.

**Comment by mmomin-crest** [comment]
Hi @vkorenkov-varonis 
Logo image in the market place for the SOAR Apps is the SVG file of this connector itself. The logo in the market place will be replaced by the SVG file that you have updated here after the app is released.

Splunkbase uses SVG file for the light mode(in this case - **logo_varonissaas.svg**). Splunkbase itself has default dark theme. Thus, black coloured logos are not visible on the Splunk base.

Please note - There are Two apps, **'Varonis SaaS'** and **'Varonis SaaS for SOAR'**. You can only change the logo of the later one(SOAR App) from this connector.

Let us know if you have any other queries.

**Comment by vkorenkov-varonis** [comment]
Hi @mmomin-crest,
The question is: can I use third one image, to be displayed in marketplace? The reason is that we have rectangular logo for Splunk App, and we have square logo for marketplace, because on the marketplace side rectangular log looks pretty badly. Is it possible to use additional image for marketplace?

**Comment by mmomin-crest** [comment]
@vkorenkov-varonis 
I asked around. And there is no way to display a different logo in the Market place.

**Review by stutib-crest — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
